### ISSUE TITLE
麻烦支持小数点后3位

### ISSUE THREAD

**Issue by lzq2357** [alexiscn/StocksBar#1]
老哥，感谢你开发的软件，用起来还可以，但是价格只显示了小数点后2位，ETF基本都是到0.001的

**Comment by alexiscn** [comment]
Please checkout [StockBar 1.3](https://github.com/alexiscn/StocksBar/releases/tag/1.3)

**Comment by lzq2357** [comment]
title 没有支持到3位小数
let title = String(format: "%@ %.2f %@", stock.symbol, stock.current, stock.displayPercent)

**Comment by alexiscn** [comment]
> title 没有支持到3位小数
> let title = String(format: "%@ %.2f %@", stock.symbol, stock.current, stock.displayPercent)

Fixed in [1.5](https://github.com/alexiscn/StocksBar/releases/tag/1.5)
