### ISSUE TITLE
科创板的股票搜不到

### ISSUE THREAD

**Issue by cuigh** [alexiscn/StocksBar#2]
如搜索“芯海科技”
![image](https://user-images.githubusercontent.com/1681556/98335556-2a9f2280-2040-11eb-967b-31e7514ee626.png)

**Comment by alexiscn** [comment]
数据源改成sina的就可以了

**Comment by alexiscn** [comment]
Release 了1.6 版本，可以搜到科创板的股票了

**Comment by cuigh** [comment]
貌似还有些问题，比如"爱博医疗(688050)"依然搜不到

**Comment by alexiscn** [comment]
> 貌似还有些问题，比如"爱博医疗(688050)"依然搜不到

Fixed in 1.7

**Comment by cuigh** [comment]
Great. It looks all right this time.
