### ISSUE TITLE
提示软件已损坏

### ISSUE THREAD

**Issue by hiperioncn** [alexiscn/StocksBar#5]
系统信息如下：
![image](https://user-images.githubusercontent.com/6045710/150057015-35de3134-719a-4c7e-af66-aee62a417379.png)

错误提示框：
![image](https://user-images.githubusercontent.com/6045710/150057085-1f9495f9-faf4-47f2-9ed3-3e63db4c7223.png)

**Comment by alexiscn** [comment]
自行Google app 已损坏的解决方案

**Comment by hiperioncn** [comment]
不好意思，已解决。
